### PR TITLE
Ruby 3 + Crawl Params for Tanakai

### PR DESCRIPTION
**Pull request by jkeen**
1. Allow passing data: {} into crawl! from this @dtengeri branch https://github.com/dtengeri/kimuraframework 
3. Ruby 3 compatibility from this @n-studio branch: https://github.com/n-studio/kimuraframework
4. Combined PR that remains stagnant on the @vifreefly repo: https://github.com/vifreefly/kimuraframework/pull/70 

This PR is that combined work plus dealing with some merge conflicts

### CODE REVIEW

**Comment by drougojrom** [comment]
hey!
thank you for all your effort, but just a small question then, do you have any plans of merging and releasing this update?

**Comment by jkeen** [comment]
If only it were up to me!

This part of the open source community is really frustrating, because I can submit PRs all day long but maintainers have to push the buttons to merge and release. The number of PRs I have just sitting out there not being paid attention to… I try not to think about it.

**Comment by glaucocustodio** [comment]
Sorry @jkeen, I missed this going on. Tanakai already got support to ruby 3, could you please open separate PR's for the other things and I will be happy to merge and cut a new version. Thanks.

**Comment by glaucocustodio** [comment]
Closing this as Tanakai already supports Ruby 3 and passing `data` to `crawl!` as well (the latter since version `1.7.0`)

**Pull request closed without merging**
